# Generated by Django 5.2.12 on 2026-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0792_fix_animated_emoji_still_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmexport",
            name="export_path_purged",
            field=models.BooleanField(default=False),
        ),
    ]
